name: Chris Hawkins
favicon: null
layout_spectrum: 0.23828962887637317
typography_spectrum: 0.37739089597016573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9379727840423584
  lightness: 0.40743634733371437
  saturation: 0.13721208134666085
  rhythmicContrast: 0.29769589751958847
purpose: []
